import { CDN_URL } from "./constants";
import type { RuleProvider } from "./types";

export const ruleProviders: Record<string, RuleProvider> = {
    ADBlock: {
        type: "http",
        behavior: "domain",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/217heidai/adblockfilters@main/rules/adblockmihomolite.yaml`,
        path: "./ruleset/ADBlock.yaml",
    },
    SogouInput: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: "https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt",
        path: "./ruleset/SogouInput.txt",
    },
    StaticResources: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: "https://ruleset.skk.moe/Clash/domainset/cdn.txt",
        path: "./ruleset/StaticResources.txt",
    },
    CDNResources: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: "https://ruleset.skk.moe/Clash/non_ip/cdn.txt",
        path: "./ruleset/CDNResources.txt",
    },
    TikTok: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Wh1zd/override-rules@main/ruleset/TikTok.list`,
        path: "./ruleset/TikTok.list",
    },
    SteamFix: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Wh1zd/override-rules@main/ruleset/SteamFix.list`,
        path: "./ruleset/SteamFix.list",
    },
    SteamCN: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml`,
        path: "./ruleset/SteamCN.yaml",
    },
    Steam: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml`,
        path: "./ruleset/Steam.yaml",
    },
    Emby: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: "https://raw.githubusercontent.com/666OS/rules/release/surge/Emby.txt",
        path: "./ruleset/Emby.txt",
    },
    GoogleFCM: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Wh1zd/override-rules@main/ruleset/FirebaseCloudMessaging.list`,
        path: "./ruleset/FirebaseCloudMessaging.list",
    },
    AdditionalFilter: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Wh1zd/override-rules@main/ruleset/AdditionalFilter.list`,
        path: "./ruleset/AdditionalFilter.list",
    },
    AdditionalCDNResources: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Wh1zd/override-rules@main/ruleset/AdditionalCDNResources.list`,
        path: "./ruleset/AdditionalCDNResources.list",
    },
    Crypto: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Wh1zd/override-rules@main/ruleset/Crypto.list`,
        path: "./ruleset/Crypto.list",
    },
    Weibo: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Wh1zd/override-rules@main/ruleset/Weibo.list`,
        path: "./ruleset/Weibo.list",
    },
    linkedin: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/blackmatrix7/ios_rule_script@master/rule/Clash/LinkedIn/LinkedIn.yaml`,
        path: "./ruleset/linkedin.yaml",
    },
    facebook: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Facebook/Facebook.yaml`,
        path: "./ruleset/facebook.yaml",
    },
    whatsapp: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Whatsapp/Whatsapp.yaml`,
        path: "./ruleset/whatsapp.yaml",
    },
    Microsoft: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml`,
        path: "./ruleset/Microsoft.yaml",
    },
    GFWList: {
        type: "http",
        behavior: "domain",
        format: "yaml",
        interval: 86400,
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt",
        path: "./ruleset/GFWList.yaml",
    },
};
